######################################################################
# Automatically generated by qmake (2.01a) Fri May 2 21:24:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

HEADERS += \
    Matrix.h \
    MatrixException.h
